import type { Provider } from './types';

export const PROVIDERS: Provider[] = [
  { id: 'anthropic', name: 'Anthropic', color: '#f472b6', endpoint: 'https://api.anthropic.com/v1/messages', type: 'anthropic', keyHint: 'sk-ant-', placeholder: 'sk-ant-...', models: [{ id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6' }, { id: 'claude-sonnet-4-20250514', name: 'Claude Sonnet 4' }, { id: 'claude-haiku-4-5-20251001', name: 'Claude Haiku 4.5' }] },
  { id: 'fireworks', name: 'Fireworks AI', color: '#fb923c', endpoint: 'https://api.fireworks.ai/inference/v1/chat/completions', type: 'openai', keyHint: 'fw_', placeholder: 'fw_3aB...', models: [{ id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', name: 'Llama 3.3 70B' }, { id: 'accounts/fireworks/models/llama-v3p1-8b-instruct', name: 'Llama 3.1 8B' }, { id: 'accounts/fireworks/models/qwen2p5-coder-32b-instruct', name: 'Qwen 2.5 Coder 32B' }] },
  { id: 'openai', name: 'OpenAI', color: '#4ade80', endpoint: 'https://api.openai.com/v1/chat/completions', type: 'openai', keyHint: 'sk-', placeholder: 'sk-...', models: [{ id: 'gpt-4o', name: 'GPT-4o' }, { id: 'gpt-4o-mini', name: 'GPT-4o Mini' }, { id: 'o3-mini', name: 'o3-mini' }] },
  { id: 'google', name: 'Google Gemini', color: '#2dd4bf', endpoint: 'https://generativelanguage.googleapis.com/v1beta', type: 'gemini', keyHint: 'AIza', placeholder: 'AIza...', models: [{ id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash' }, { id: 'gemini-2.5-pro-exp-03-25', name: 'Gemini 2.5 Pro' }] },
  { id: 'groq', name: 'Groq', color: '#facc15', endpoint: 'https://api.groq.com/openai/v1/chat/completions', type: 'openai', keyHint: 'gsk_', placeholder: 'gsk_...', models: [{ id: 'llama-3.3-70b-specdec', name: 'Llama 3.3 70B' }, { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B' }, { id: 'qwen-2.5-32b', name: 'Qwen 2.5 32B' }] },
  { id: 'together', name: 'Together AI', color: '#818cf8', endpoint: 'https://api.together.xyz/v1/chat/completions', type: 'openai', keyHint: 'tgp_', placeholder: 'tgp_...', models: [{ id: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', name: 'Llama 3.1 8B' }, { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' }, { id: 'Qwen/Qwen2.5-7B-Instruct-Turbo', name: 'Qwen 2.5 7B' }] },
  { id: 'openrouter', name: 'OpenRouter', color: '#a78bfa', endpoint: 'https://openrouter.ai/api/v1/chat/completions', type: 'openai', keyHint: 'sk-or-', placeholder: 'sk-or-...', models: [{ id: 'google/gemini-2.0-flash-001', name: 'Gemini 2.0 Flash' }, { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B' }, { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini' }] },
  { id: 'openzen', name: 'OpenZen', color: '#6366f1', endpoint: '/zen-proxy/v1/chat/completions', type: 'openai', keyHint: 'zen-', placeholder: 'zen-...', models: [{ id: 'default', name: 'Default' }] },
  { id: 'mistral', name: 'Mistral', color: '#38bdf8', endpoint: 'https://api.mistral.ai/v1/chat/completions', type: 'openai', keyHint: 'xVH', placeholder: 'xVH...', models: [{ id: 'mistral-large-2411', name: 'Mistral Large' }, { id: 'mistral-small-2501', name: 'Mistral Small' }, { id: 'ministral-3b-2410', name: 'Ministral 3B' }] },
];
